# Generated by Django 2.2.7 on 2019-11-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Backend',
        ),
    ]
